<Project>
	<PropertyGroup>
		<ProductVersion>0.7.0</ProductVersion>
		<Version Condition=" '$(ProductVersion)' == '' ">0.0.1</Version>
		<Version Condition=" '$(ProductVersion)' != '' ">$(ProductVersion)</Version>
	</PropertyGroup>	

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>Todd Lang</Authors>
		<Description>Provides a consistent abstraction for large buffers and performing repetitive operations on those buffers.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/kiyote/Kiyote.Buffers</PackageProjectUrl>
		<RepositoryUrl>https://github.com/kiyote/Kiyote.Buffers</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<PropertyGroup>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>
</Project>
