name: Release

on:
  create:
    branches: 
      - release/**

env:
  DOTNET_VERSION: 8.0.401
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION }}

      - name: Define global.json
        run: dotnet new globaljson --sdk-version ${{ env.DOTNET_VERSION }}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore
        run: nuget restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
